---
- name: "Add archlinux.fr repo to pacman.conf"
  lineinfile:
    dest: "/etc/pacman.conf"
    state: "present"
    line: "{{ item }}"
  with_items:
    - "[archlinuxfr]"
    - "SigLevel = Never"
    - "Server = http://repo.archlinux.fr/$arch"
    
- name: "Install yaourt"
  pacman:
    name: "yaourt"
    state: "present"
    update_cache: yes