---
sudo: required

env:
- distribution: archlinux/base
  version: latest
  name: archsible

# Docker is already launched by default, but better safe than sorry
services:
  - docker

before_install:
  - 'sudo docker pull ${distribution}:${version}'
  - 'sudo docker build --no-cache --rm --file=travis/Dockerfile --tag=${name} travis'

script:
  - container_id=$(mktemp)
  - 'sudo docker run --detach --privileged --volume="${PWD}":/home/ansible:ro ${name} ANSIBLE_FORCE_COLOR=1 ansible-playbook -v /home/ansible/playbook.yml --syntax-check -i hosts'
  - 'sudo docker run --detach --privileged --volume="${PWD}":/home/ansible:ro ${name} ANSIBLE_FORCE_COLOR=1 ansible-playbook -v /home/ansible/playbook.yml -i hosts'
