---
sudo: required

env:
- distribution: archlinux/base
  version: latest
  name: archsible

services:
  - docker

before_install:
  - 'sudo docker pull ${distribution}:${version}'
  - 'sudo docker build --no-cache --rm --file=travis/Dockerfile --tag=${name} travis'

script:
  - container_id=$(mktemp)
  - 'sudo docker run --detach --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro --volume="${PWD}":/home/ansible:ro ${name} > "${container_id}"'
  - 'sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v /home/ansible/playbook.yml --syntax-check -i hosts'
  - 'sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v /home/ansible/playbook.yml -i hosts'
  - 'sudo docker rm -f "$(cat ${container_id})"'