---
- name: Install vscode
  pacman:
    name: code 

- name: Install vscode extensions
  command: code-oss --install-extension {{item}}
  become: yes
  become_user: "{{ user_name }}"
  with_items:
  - vscoss.vscode-ansible
  - haaaad.ansible
  - icrawl.discord-vscode
  - PeterJausovec.vscode-docker
  - donjayamanne.githistory
  - codezombiech.gitignore
  - dasfranck.jellybeans
  - wholroyd.jinja
  - christian-kohler.path-intellisense
  - ms-python.python
  - vscodevim.vim
  - wayou.vscode-todo-highlight
  - robertohuertasm.vscode-icons

- name: Copy vscode configuration
  copy:
    src: /tmp/dotfiles/.config/Code - OSS
    dest: /home/{{ user_name }}/.config/Code - OSS
    owner: "{{ user_name }}"
    group: users