---
- name: Installing zsh and git
  pacman: name={{ item }} state=present
  with_items:
    - zsh
    - git
  register: installation

- name: Backing up existing ~/.zshrc
  shell: if [ -f /home/{{ user_name }}/.zshrc ]; then mv /home/{{ user_name }}/.zshrc{,.orig}; fi
  when: 'installation is success'
  sudo: no

- name: Cloning oh-my-zsh
  git:
    repo=https://github.com/robbyrussell/oh-my-zsh
    dest=/home/{{ user_name }}/.oh-my-zsh
  when: 'installation is success'
  register: cloning
  sudo: no

- name: Creating new ~/.zshrc
  copy:
    src=/home/{{ user_name }}/.oh-my-zsh/templates/zshrc.zsh-template
    dest=/home/{{ user_name }}/.zshrc
  when: 'cloning is success'
  sudo: no
