---
- name: Install dtrx
  aur:
    name: dtrx
  become: yes
  become_user: aur
  tags: aur

- name: Install optionnal dependencies
  pacman:
    name: {{ item }}
  with_items:
  - p7zip
  - tar
  - unzip
  - unrar
  - gzip
  - bzip2
  tags: aur #Tagged as aur because it's pointless without previous step
