---
- name: Install python 2 & 3 and their python-pip
  pacman: 
    name: {{ item }}
  with_items:
    - python
    - python-pip
    - python2
    - python2-pip

- name: Install ipython, virtualenv and flake8
  pip:
    name: "{{ item }}"
    executable: pip
  with_items:
    - ipython
    - virtualenv
    - flake8
