---
- name: Install python 3 and python-pip
  pacman: name={{ item }} state=present
  with_items:
    - python
    - python-pip

- name: Install ipython, virtualenv and flake8
  pip:
    name: "{{ item }}"
    executable: pip #Meant to be pip-3 on arch
  with_items:
    - ipython
    - virtualenv
    - flake8