---
- name: Install python 2 & 3 and their python-pip
  pacman: 
    name: "{{ item }}"
  with_items:
    - python
    - python-pip
    - python2
    - python2-pip
    - ipython
    - python-virtualenv

- name: Install ipython, virtualenv and flake8 as {{ user_name }} 
  pip:
    name: "{{ item }}"
    executable: pip
  with_items:
    - ipython
    - virtualenv
    - flake8
  become: yes
  become_user: "{{ user_name }}" 
