---
- name: Install packages from official repos
  pacman: name={{ item }} state=present
  with_items:
    - sddm
    - i3-gaps
    - conky
    - compton
    - feh
    - rofi
#    - i3lock/slimlock

- name: Install polybar from AUR
  aur: name={{ item }} use=yay skip_installed=yes
  with_items:
    - polybar
  become: yes
  become_user: aur

- name: Get Meslo LG M DZ Mono font
  get_url:
    url: https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/Meslo/M-DZ/complete/Meslo%20LG%20M%20DZ%20Regular%20Nerd%20Font%20Complete%20Mono.otf
    dest: /home/{{ user_name }}/.local/share/fonts/MLG.otf

#TODO CONFIG SDDM

- name: Copy i3 configuration
  copy:
    src: /tmp/dotfiles/.i3
    dest: /home/{{ user_name }}/.i3

#TODO CONFIG SLIMLOCK

- name: Copy conky configuration
  copy:
    src: /tmp/dotfiles/.conkyrc
    dest: /home/{{ user_name }}/.conkyrc

- name: Copy polybar configuration
  copy:
    src: /tmp/dotfiles/.config/polybar
    dest: /home/{{ user_name }}/.config/polybar

- name: Set rofi theme to sidebar
  lineinfile:
    create: yes
    path: /home/{{ user_name }}/.config/rofi/config
    line: "rofi.theme: /usr/share/rofi/themes/sidebar.rasi"