---
- name: Install packages from official repos
  pacman: name={{ item }} state=present
  with_items:
    - lightdm
    - i3-gaps
    - conky
    - compton
    - feh
    - rofi

# Broken: https://github.com/ansible/ansible/issues/36585
##- name: Enable lightdm
##  service:
##    name: lightdm
##    enabled: yes

- name: Enable lightdm
  shell: systemctl enable lightdm

- name: Install polybar and lightdm theme from AUR
  aur: name={{ item }} use=yay skip_installed=yes
  with_items:
    - polybar
    - lightdm-webkit-theme-litarvan
  become: yes
  become_user: aur
  tags: aur

- name: Set lightdm greeter to webkit2
  replace:
    path: /etc/lightdm/lightdm.conf
    regexp: '#greeter-session=.*$'
    replace: 'greeter-session=lightdm-webkit2-greeter'
    after: '\[Seat:\*\]'
    backup: yes

- name: Set lightdm greeter theme to litarvan
  replace:
    path: /etc/lightdm/lightdm-webkit2-greeter.conf
    regexp: 'webkit_theme.*=.+$'
    replace: 'webkit_theme=litarvan'
    backup: yes

- name: Rank pacman's mirrors
  shell: rankmirrors /etc/pacman.d/mirrorlist.ansible > /etc/pacman.d/mirrorlist

- name: pacman -Syu
  pacman:
    update_cache: yes
    upgrade: yes

- name: Install zsh, man, htop, curl, tmux, vim, which, openssh and tar
  pacman: name={{ item }} state=present
  with_items:
    - base
    - htop
    - curl
    - vim
    - sudo
    - openssh

- name: Create /home/{{ user_name }}/.local/share/fonts/
  file:
    path: /home/{{ user_name }}/.local/share/fonts/
    state: directory
    mode: 0755

- name: Get Meslo LG M DZ Mono font
  get_url:
    url: https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/Meslo/M-DZ/complete/Meslo%20LG%20M%20DZ%20Regular%20Nerd%20Font%20Complete%20Mono.otf
    dest: /home/{{ user_name }}/.local/share/fonts/MLG.otf

#TODO CONFIG SDDM

- name: Copy i3 configuration
  copy:
    src: /tmp/dotfiles/.i3
    dest: /home/{{ user_name }}/.i3

#TODO CONFIG SLIMLOCK

- name: Copy conky configuration
  copy:
    src: /tmp/dotfiles/.conkyrc
    dest: /home/{{ user_name }}/.conkyrc

- name: Copy polybar configuration
  copy:
    src: /tmp/dotfiles/.config/polybar
    dest: /home/{{ user_name }}/.config/polybar

- name: Set rofi theme to sidebar
  lineinfile:
    create: yes
    path: /home/{{ user_name }}/.config/rofi/config
    line: "rofi.theme: /usr/share/rofi/themes/sidebar.rasi"

- name: Set .xinitrc to i3
  lineinfile:
    create: yes
    path: /home/{{ user_name }}/.xinitrc
    line: "exec i3"
