---
- name: Install packages from official repos
  pacman: name={{ item }} state=present
  with_items:
    - xorg-server
    - xorg-xbacklight
    - xf86-video-intel
    - ttf-dejavu
    - ttf-freefont
    - ttf-roboto
    - noto-fonts
    - lightdm
    - i3-gaps
    - conky
    - compton
    - feh
    - rofi
    - light-locker
    - network-manager-applet

- name: Reload systemd daemons
  systemd:
    daemon-reload: yes
  tags:
    - notravis

- name: Enable lightdm
  systemd:
    name: lightdm
    enabled: yes
  tags:
    - notravis

- name: Install polybar and lightdm theme from AUR
  aur: name={{ item }}
  with_items:
    - polybar
    - lightdm-webkit-theme-litarvan
  become: yes
  become_user: aur
  tags: aur

- name: Set lightdm greeter to webkit2
  replace:
    path: /etc/lightdm/lightdm.conf
    regexp: '#greeter-session=.*$'
    replace: 'greeter-session=lightdm-webkit2-greeter'
    after: '\[Seat:\*\]'
    backup: yes

- name: Set lightdm greeter theme to litarvan
  copy:
    src: /tmp/dotfiles/etc/lightdm/lightdm-webkit2-greeter.conf
    dest: /etc/lightdm/lightdm-webkit2-greeter.conf

- name: Create /home/{{ user_name }}/.local/share/fonts/
  file:
    path: /home/{{ user_name }}/.local/share/fonts/
    state: directory
    mode: 0755

- name: Get Meslo LG M DZ Mono font
  get_url:
    url: https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/Meslo/M-DZ/Regular/complete/Meslo%20LG%20M%20DZ%20Regular%20Nerd%20Font%20Complete%20Mono.ttf?raw=true
    dest: /home/{{ user_name }}/.local/share/fonts/MLG.ttf

- name: Get Meslo LG M DZ Mono bold font
  get_url:
    url: https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/Meslo/M-DZ/Bold/complete/Meslo%20LG%20M%20DZ%20Bold%20Nerd%20Font%20Complete%20Mono.ttf?raw=true
    dest: /home/{{ user_name }}/.local/share/fonts/MLG-bold.ttf

- name: Get Meslo LG M DZ Mono italic font
  get_url:
    url: https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/Meslo/M-DZ/Italic/complete/Meslo%20LG%20M%20DZ%20Italic%20Nerd%20Font%20Complete%20Mono.ttf?raw=true
    dest: /home/{{ user_name }}/.local/share/fonts/MLG-italic.ttf

- name: Get Meslo LG M DZ Mono bold italic font
  get_url:
    url: https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/Meslo/M-DZ/Bold-Italic/complete/Meslo%20LG%20M%20DZ%20Bold%20Italic%20Nerd%20Font%20Complete%20Mono.ttf?raw=true
    dest: /home/{{ user_name }}/.local/share/fonts/MLG-bold-italic.ttf

- name: Copy xprofile configuration
  copy:
    src: /tmp/dotfiles/.xprofile
    dest: /home/{{ user_name }}/.xprofile

- name: Copy i3 configuration
  copy:
    src: /tmp/dotfiles/.i3/
    dest: /home/{{ user_name }}/.config/.i3

- name: Copy conky configuration
  copy:
    src: /tmp/dotfiles/.conkyrc
    dest: /home/{{ user_name }}/.conkyrc

- name: Copy polybar configuration
  copy:
    src: /tmp/dotfiles/.config/polybar
    dest: /home/{{ user_name }}/.config/

- name: Set rofi theme to sidebar
  lineinfile:
    create: yes
    path: /home/{{ user_name }}/.config/rofi/config
    line: "rofi.theme: /usr/share/rofi/themes/sidebar.rasi"

- name: Set .xinitrc to i3
  lineinfile:
    create: yes
    path: /home/{{ user_name }}/.xinitrc
    line: "exec i3"

- name: Install i3-scrot
  aur:
    name: i3-scrot
    use: yay
  become: yes
  become_user: aur
  tags: aur
