---
- name: Install weechat
  pacman: name={{ item }} state=present
  with_items:
    - weechat

- name: Install discord from AUR
  aur: name={{ item }} use=yay skip_installed=yes
  with_items:
    - discord
  become: yes
  become_user: aur
  tags: aur