---
- name: Install some beloved apps
  pacman:
    name: "{{ item }}"
  with_items:
    - firefox
    - thunderbird
    - syncthing
    - dolphin
    - termite
    - keepassx2

- name: Reload systemd daemons
  systemd:
    daemon-reload: yes
  tags:
    - notravis

- name: Enable syncthing
  systemd:
    enabled: yes
    state: started
    name: syncthing@{{ user_name }}
  tags:
    - notravis

- name: Copy termite configuration
  copy:
    src: /tmp/dotfiles/.config/termite
    dest: /home/{{ user_name }}/.config/termite

- name: Copy rofi configuration
  copy:
    src: /tmp/dotfiles/.config/rofi
    dest: /home/{{ user_name }}/.config/rofi
