---
- name: Install some beloved apps
  pacman: name={{ item }} state=present
  with_items:
    - firefox
    - syncthing
    - dolphin
    - terminology
    - keepassx2

- name: Enable syncthing
  shell: systemctl enable syncthing@{{ user_name }}