---
- name: Install some beloved apps
  pacman: name={{ item }} state=present
  with_items:
    - firefox
    - thunderbird
    - syncthing
    - dolphin
    - terminology
    - keepassx2

- name: Reload systemd daemons
  systemd:
    daemon-reload: yes
  tags:
    - notravis

- name: Enable syncthing
  systemd:
      enabled: yes
      state: started
      name: syncthing@{{ user_name }}
  tags:
    - notravis
