- name: Install some cli tools
  pacman:
    name:
      - links
      - ranger
      - ncdu
      - tree
      - tmux
      - lsd
      - neofetch

- name: Copy git configuration
  copy:
    src: /tmp/dotfiles/.gitconfig
    dest: /home/{{ user_name }}/.gitconfig
    owner: "{{ user_name }}"
    group: users

- name: Copy tmux configuration
  copy:
    src: /tmp/dotfiles/.tmux.conf
    dest: /home/{{ user_name }}/.tmux.conf
    owner: "{{ user_name }}"
    group: users
