---
- name: Install several media applications
  pacman:
    name: {{ item }}
  with_items:
  - vlc
  - clementine
  - audacity
  - libreoffice-fresh
  - digikam
  - hugin
  - pavucontrol

- name: Install spotify from AUR
  aur:
    name: {{ item }}
    use: yay
  with_items:
    - spotify
  become: yes
  become_user: aur
  tags: aur
