---
- name: Install vim and neovim
  pacman: name={{ item }} state=present
  with_items:
    - vim
    - neovim
    - python-neovim
    - python-jedi

- name: Create the directory for neovim's vim-plug
  file:
    path: /home/{{ user_name }}/.config/nvim/autoload/
    state: directory

- name: Install vim-plug for neovim
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: /{{ user_name }}/.config/nvim/autoload/plug.vim

- name: Copy init.vim
  copy:
    src: /tmp/dotfiles/.config/nvim/init.vim
    dest: /home/{{ user_name }}/.config/nvim/init.vim